In [1]:
import pandas as pd

In [2]:
c_df = pd.read_csv("../CSV Files/Core_Metrics_Zip_History.csv")
c_df.head()

,month_date_yyyymm,postal_code,state,city_name,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,...,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag,county_name
0,2023-09,55127,MN,Saint Paul,635000.0,-0.0483,-0.0344,53.0,0.1158,0.5143,...,-0.0398,0.0555,106.0,0.0872,0.3250,0.9434,-0.1092,-0.3423,0.0,Ramsey
1,2023-09,18354,PA,Sciota,399999.0,0.0000,0.3560,2.0,-0.3333,-0.5000,...,0.0000,0.1676,3.0,-0.4000,-0.5000,1.0000,-0.1667,0.6250,1.0,Monroe
2,2023-09,35593,AL,Vina,275000.0,0.1305,0.7416,1.0,0.0000,-0.8000,...,0.1305,0.4634,2.0,0.0000,-0.6667,1.0000,0.0000,0.8000,1.0,Franklin
3,2023-09,85295,AZ,Gilbert,625000.0,-0.0056,0.0994,72.0,0.0746,-0.5944,...,-0.0196,0.1102,112.0,-0.0968,-0.5634,0.5694,-0.1917,0.1216,0.0,Maricopa
4,2023-09,94970,CA,Stinson Beach,7495000.0,0.0000,-0.2004,2.0,0.0000,0.0000,...,0.4181,0.0465,2.0,-0.6000,-0.4286,0.5000,-1.0000,-0.2500,1.0,Marin

In [3]:
h_df = pd.read_csv("../CSV Files/Hotness_Metrics_Zip_History.csv")
h_df.head()

,month_date_yyyymm,postal_code,state,city_name,nielsen_hh_rank,hotness_rank,hotness_rank_mm,hotness_rank_yy,hotness_score,supply_score,...,median_dom_vs_us,ldp_unique_viewers_per_property_mm,ldp_unique_viewers_per_property_yy,ldp_unique_viewers_per_property_vs_us,median_listing_price,median_listing_price_mm,median_listing_price_yy,median_listing_price_vs_us,quality_flag,county_name
0,2023-09,14450,NY,Fairport,998.0,1.0,-5.0,0.0,99.978698,99.974438,...,-41.0,0.100652,-0.123400,4.949911,369000.0,-0.065586,0.126976,0.859139,0.0,Monroe
1,2023-09,4106,ME,South Portland,3627.0,2.0,-2.0,NaN,99.923313,99.906271,...,-39.0,-0.063090,-0.011696,4.677433,580000.0,-0.004292,0.341040,1.350407,0.0,Cumberland
2,2023-09,14624,NY,Rochester,1837.0,3.0,-4.0,1.0,99.919052,99.965917,...,-40.0,0.022460,-0.013447,4.311374,214900.0,0.075038,0.132991,0.500349,0.0,Monroe
3,2023-09,6111,CT,Newington,3095.0,4.0,-1064.0,-15.0,99.897751,99.838105,...,-38.0,0.414016,-0.002990,4.794335,294950.0,-0.051608,-0.028651,0.686729,0.0,Hartford
4,2023-09,1970,MA,Salem,884.0,5.0,-7.0,-5.0,99.893490,99.889230,...,-38.5,0.122447,0.133164,4.435820,521950.0,0.105416,0.021079,1.215250,0.0,Essex

In [4]:
c_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2395931 entries, 0 to 2395930
Data columns (total 42 columns):
 #   Column                                   Dtype
---  ------                                   -----
 0   month_date_yyyymm                        object
 1   postal_code                              int64
 2   state                                    object
 3   city_name                                object
 4   median_listing_price                     float64
 5   median_listing_price_mm                  float64
 6   median_listing_price_yy                  float64
 7   active_listing_count                     float64
 8   active_listing_count_mm                  float64
 9   active_listing_count_yy                  float64
 10  median_days_on_market                    float64
 11  median_days_on_market_mm                 float64
 12  median_days_on_market_yy                 float64
 13  new_listing_count                        float64
 14  new_listing_count_mm                     float64
 15  new_listing_count_yy                     float64
 16  price_increased_count                    float64
 17  price_increased_count_mm                 float64
 18  price_increased_count_yy                 float64
 19  price_reduced_count                      float64
 20  price_reduced_count_mm                   float64
 21  price_reduced_count_yy                   float64
 22  pending_listing_count                    float64
 23  pending_listing_count_mm                 float64
 24  pending_listing_count_yy                 float64
 25  median_listing_price_per_square_foot     float64
 26  median_listing_price_per_square_foot_mm  float64
 27  median_listing_price_per_square_foot_yy  float64
 28  median_square_feet                       float64
 29  median_square_feet_mm                    float64
 30  median_square_feet_yy                    float64
 31  average_listing_price                    float64
 32  average_listing_price_mm                 float64
 33  average_listing_price_yy                 float64
 34  total_listing_count                      float64
 35  total_listing_count_mm                   float64
 36  total_listing_count_yy                   float64
 37  pending_ratio                            float64
 38  pending_ratio_mm                         float64
 39  pending_ratio_yy                         float64
 40  quality_flag                             float64
 41  county_name                              object
dtypes: float64(37), int64(1), object(4)
memory usage: 767.7+ MB

In [5]:
h_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 926158 entries, 0 to 926157
Data columns (total 26 columns):
 #   Column                                 Non-Null Count   Dtype
---  ------                                 --------------   -----
 0   month_date_yyyymm                      926158 non-null  object
 1   postal_code                            926158 non-null  int64
 2   state                                  926158 non-null  object
 3   city_name                              926158 non-null  object
 4   nielsen_hh_rank                        926158 non-null  float64
 5   hotness_rank                           926158 non-null  float64
 6   hotness_rank_mm                        876941 non-null  float64
 7   hotness_rank_yy                        688283 non-null  float64
 8   hotness_score                          926158 non-null  float64
 9   supply_score                           926158 non-null  float64
 10  demand_score                           926158 non-null  float64
 11  median_days_on_market                  926157 non-null  float64
 12  median_days_on_market_mm               926153 non-null  float64
 13  median_dom_mm_day                      926153 non-null  float64
 14  median_days_on_market_yy               926074 non-null  float64
 15  median_dom_yy_day                      926074 non-null  float64
 16  median_dom_vs_us                       926157 non-null  float64
 17  ldp_unique_viewers_per_property_mm     910157 non-null  float64
 18  ldp_unique_viewers_per_property_yy     743856 non-null  float64
 19  ldp_unique_viewers_per_property_vs_us  926158 non-null  float64
 20  median_listing_price                   926158 non-null  float64
 21  median_listing_price_mm                926155 non-null  float64
 22  median_listing_price_yy                926081 non-null  float64
 23  median_listing_price_vs_us             926158 non-null  float64
 24  quality_flag                           926158 non-null  float64
 25  county_name                            926081 non-null  object
dtypes: float64(21), int64(1), object(4)
memory usage: 183.7+ MB

In [6]:
# merge the dataframes
combo_df = pd.merge(h_df, c_df, on=['postal_code', 'month_date_yyyymm'])

In [7]:
combo_df

,month_date_yyyymm,postal_code,state_x,city_name_x,nielsen_hh_rank,hotness_rank,hotness_rank_mm,hotness_rank_yy,hotness_score,supply_score,...,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag_y,county_name_y
0,2023-09,14450,NY,Fairport,998.0,1.0,-5.0,0.0,99.978698,99.974438,...,-0.1090,0.1193,26.0,0.1556,0.0000,0.1667,0.0691,-0.0476,0.0,Monroe
1,2023-09,4106,ME,South Portland,3627.0,2.0,-2.0,NaN,99.923313,99.906271,...,0.0503,0.0367,27.0,0.2857,0.6875,0.2727,0.1675,0.0327,1.0,Cumberland
2,2023-09,14624,NY,Rochester,1837.0,3.0,-4.0,1.0,99.919052,99.965917,...,0.0970,0.1037,20.0,-0.0476,-0.1837,0.1765,0.0376,0.0602,0.0,Monroe
3,2023-09,6111,CT,Newington,3095.0,4.0,-1064.0,-15.0,99.897751,99.838105,...,-0.0268,-0.0417,65.0,-0.0299,-0.3085,3.2667,-0.0146,0.9274,0.0,Hartford
4,2023-09,1970,MA,Salem,884.0,5.0,-7.0,-5.0,99.893490,99.889230,...,0.0739,0.0137,35.0,0.4583,-0.3069,0.4000,0.0176,0.0667,0.0,Essex
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
926153,2017-08,10006,NY,New York,11956.0,16084.0,NaN,NaN,0.366756,0.491080,...,0.0871,-0.0263,109.0,-0.0726,0.3232,0.7724,0.1913,0.1091,0.0,New York
926154,2017-08,83113,WY,Big Piney,17292.0,16085.0,NaN,NaN,0.351215,0.217567,...,0.0368,-0.0536,47.0,0.0333,0.4531,0.0698,-0.0017,0.0031,0.0,Sublette
926155,2017-08,96024,CA,Douglas City,22139.0,16086.0,NaN,NaN,0.298378,0.180270,...,-0.0147,0.3181,23.0,0.0714,0.1842,0.0465,-0.1114,-0.2035,1.0,Trinity
926156,2017-08,87829,NM,Quemado,26077.0,16087.0,NaN,NaN,0.254864,0.236216,...,0.0566,0.2190,20.0,-0.0476,0.4286,0.0526,0.0026,NaN,0.0,Catron
926157,2017-08,36108,AL,Montgomery,6350.0,16088.0,NaN,NaN,0.087027,0.024865,...,0.2576,-0.1454,71.0,0.0143,0.3524,0.2119,0.0424,0.0828,1.0,Montgomery

In [8]:
combo_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 926158 entries, 0 to 926157
Data columns (total 66 columns):
 #   Column                                   Non-Null Count   Dtype
---  ------                                   --------------   -----
 0   month_date_yyyymm                        926158 non-null  object
 1   postal_code                              926158 non-null  int64
 2   state_x                                  926158 non-null  object
 3   city_name_x                              926158 non-null  object
 4   nielsen_hh_rank                          926158 non-null  float64
 5   hotness_rank                             926158 non-null  float64
 6   hotness_rank_mm                          876941 non-null  float64
 7   hotness_rank_yy                          688283 non-null  float64
 8   hotness_score                            926158 non-null  float64
 9   supply_score                             926158 non-null  float64
 10  demand_score                             926158 non-null  float64
 11  median_days_on_market_x                  926157 non-null  float64
 12  median_days_on_market_mm_x               926153 non-null  float64
 13  median_dom_mm_day                        926153 non-null  float64
 14  median_days_on_market_yy_x               926074 non-null  float64
 15  median_dom_yy_day                        926074 non-null  float64
 16  median_dom_vs_us                         926157 non-null  float64
 17  ldp_unique_viewers_per_property_mm       910157 non-null  float64
 18  ldp_unique_viewers_per_property_yy       743856 non-null  float64
 19  ldp_unique_viewers_per_property_vs_us    926158 non-null  float64
 20  median_listing_price_x                   926158 non-null  float64
 21  median_listing_price_mm_x                926155 non-null  float64
 22  median_listing_price_yy_x                926081 non-null  float64
 23  median_listing_price_vs_us               926158 non-null  float64
 24  quality_flag_x                           926158 non-null  float64
 25  county_name_x                            926081 non-null  object
 26  state_y                                  926158 non-null  object
 27  city_name_y                              926158 non-null  object
 28  median_listing_price_y                   926158 non-null  float64
 29  median_listing_price_mm_y                926155 non-null  float64
 30  median_listing_price_yy_y                926081 non-null  float64
 31  active_listing_count                     926158 non-null  float64
 32  active_listing_count_mm                  926154 non-null  float64
 33  active_listing_count_yy                  926058 non-null  float64
 34  median_days_on_market_y                  926157 non-null  float64
 35  median_days_on_market_mm_y               926153 non-null  float64
 36  median_days_on_market_yy_y               926074 non-null  float64
 37  new_listing_count                        926158 non-null  float64
 38  new_listing_count_mm                     893669 non-null  float64
 39  new_listing_count_yy                     889211 non-null  float64
 40  price_increased_count                    926158 non-null  float64
 41  price_increased_count_mm                 232049 non-null  float64
 42  price_increased_count_yy                 254206 non-null  float64
 43  price_reduced_count                      926158 non-null  float64
 44  price_reduced_count_mm                   832500 non-null  float64
 45  price_reduced_count_yy                   828115 non-null  float64
 46  pending_listing_count                    862095 non-null  float64
 47  pending_listing_count_mm                 843412 non-null  float64
 48  pending_listing_count_yy                 812582 non-null  float64
 49  median_listing_price_per_square_foot     925893 non-null  float64
 50  median_listing_price_per_square_foot_mm  925783 non-null  float64
 51  median_listing_price_per_square_foot_yy  925696 non-null  float64
 52  median_square_feet                       925897 non-null  float64
 53  median_square_feet_mm                    925789 non-null  float64
 54  median_square_feet_yy                    925701 non-null  float64
 55  average_listing_price                    926158 non-null  float64
 56  average_listing_price_mm                 926155 non-null  float64
 57  average_listing_price_yy                 926081 non-null  float64
 58  total_listing_count                      926158 non-null  float64
 59  total_listing_count_mm                   926156 non-null  float64
 60  total_listing_count_yy                   926094 non-null  float64
 61  pending_ratio                            862095 non-null  float64
 62  pending_ratio_mm                         849376 non-null  float64
 63  pending_ratio_yy                         820766 non-null  float64
 64  quality_flag_y                           926158 non-null  float64
 65  county_name_y                            926081 non-null  object
dtypes: float64(58), int64(1), object(7)
memory usage: 473.4+ MB

In [9]:
print(combo_df.columns)

Index(['month_date_yyyymm', 'postal_code', 'state_x', 'city_name_x',
       'nielsen_hh_rank', 'hotness_rank', 'hotness_rank_mm', 'hotness_rank_yy',
       'hotness_score', 'supply_score', 'demand_score',
       'median_days_on_market_x', 'median_days_on_market_mm_x',
       'median_dom_mm_day', 'median_days_on_market_yy_x', 'median_dom_yy_day',
       'median_dom_vs_us', 'ldp_unique_viewers_per_property_mm',
       'ldp_unique_viewers_per_property_yy',
       'ldp_unique_viewers_per_property_vs_us', 'median_listing_price_x',
       'median_listing_price_mm_x', 'median_listing_price_yy_x',
       'median_listing_price_vs_us', 'quality_flag_x', 'county_name_x',
       'state_y', 'city_name_y', 'median_listing_price_y',
       'median_listing_price_mm_y', 'median_listing_price_yy_y',
       'active_listing_count', 'active_listing_count_mm',
       'active_listing_count_yy', 'median_days_on_market_y',
       'median_days_on_market_mm_y', 'median_days_on_market_yy_y',
       'new_listing_count', 'new_listing_count_mm', 'new_listing_count_yy',
       'price_increased_count', 'price_increased_count_mm',
       'price_increased_count_yy', 'price_reduced_count',
       'price_reduced_count_mm', 'price_reduced_count_yy',
       'pending_listing_count', 'pending_listing_count_mm',
       'pending_listing_count_yy', 'median_listing_price_per_square_foot',
       'median_listing_price_per_square_foot_mm',
       'median_listing_price_per_square_foot_yy', 'median_square_feet',
       'median_square_feet_mm', 'median_square_feet_yy',
       'average_listing_price', 'average_listing_price_mm',
       'average_listing_price_yy', 'total_listing_count',
       'total_listing_count_mm', 'total_listing_count_yy', 'pending_ratio',
       'pending_ratio_mm', 'pending_ratio_yy', 'quality_flag_y',
       'county_name_y'],
      dtype='object')

In [10]:
# delete duplicate columns shared by both dataframes
col_to_delete = ['county_name_x',
       'state_y', 'city_name_y', 'median_listing_price_y',
       'median_listing_price_mm_y', 'median_listing_price_yy_y', 'median_days_on_market_y',
       'median_days_on_market_mm_y', 'median_days_on_market_yy_y', 'quality_flag_y',
       'county_name_y']
combo_df = combo_df.drop(columns=col_to_delete)
combo_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 926158 entries, 0 to 926157
Data columns (total 55 columns):
 #   Column                                   Non-Null Count   Dtype
---  ------                                   --------------   -----
 0   month_date_yyyymm                        926158 non-null  object
 1   postal_code                              926158 non-null  int64
 2   state_x                                  926158 non-null  object
 3   city_name_x                              926158 non-null  object
 4   nielsen_hh_rank                          926158 non-null  float64
 5   hotness_rank                             926158 non-null  float64
 6   hotness_rank_mm                          876941 non-null  float64
 7   hotness_rank_yy                          688283 non-null  float64
 8   hotness_score                            926158 non-null  float64
 9   supply_score                             926158 non-null  float64
 10  demand_score                             926158 non-null  float64
 11  median_days_on_market_x                  926157 non-null  float64
 12  median_days_on_market_mm_x               926153 non-null  float64
 13  median_dom_mm_day                        926153 non-null  float64
 14  median_days_on_market_yy_x               926074 non-null  float64
 15  median_dom_yy_day                        926074 non-null  float64
 16  median_dom_vs_us                         926157 non-null  float64
 17  ldp_unique_viewers_per_property_mm       910157 non-null  float64
 18  ldp_unique_viewers_per_property_yy       743856 non-null  float64
 19  ldp_unique_viewers_per_property_vs_us    926158 non-null  float64
 20  median_listing_price_x                   926158 non-null  float64
 21  median_listing_price_mm_x                926155 non-null  float64
 22  median_listing_price_yy_x                926081 non-null  float64
 23  median_listing_price_vs_us               926158 non-null  float64
 24  quality_flag_x                           926158 non-null  float64
 25  active_listing_count                     926158 non-null  float64
 26  active_listing_count_mm                  926154 non-null  float64
 27  active_listing_count_yy                  926058 non-null  float64
 28  new_listing_count                        926158 non-null  float64
 29  new_listing_count_mm                     893669 non-null  float64
 30  new_listing_count_yy                     889211 non-null  float64
 31  price_increased_count                    926158 non-null  float64
 32  price_increased_count_mm                 232049 non-null  float64
 33  price_increased_count_yy                 254206 non-null  float64
 34  price_reduced_count                      926158 non-null  float64
 35  price_reduced_count_mm                   832500 non-null  float64
 36  price_reduced_count_yy                   828115 non-null  float64
 37  pending_listing_count                    862095 non-null  float64
 38  pending_listing_count_mm                 843412 non-null  float64
 39  pending_listing_count_yy                 812582 non-null  float64
 40  median_listing_price_per_square_foot     925893 non-null  float64
 41  median_listing_price_per_square_foot_mm  925783 non-null  float64
 42  median_listing_price_per_square_foot_yy  925696 non-null  float64
 43  median_square_feet                       925897 non-null  float64
 44  median_square_feet_mm                    925789 non-null  float64
 45  median_square_feet_yy                    925701 non-null  float64
 46  average_listing_price                    926158 non-null  float64
 47  average_listing_price_mm                 926155 non-null  float64
 48  average_listing_price_yy                 926081 non-null  float64
 49  total_listing_count                      926158 non-null  float64
 50  total_listing_count_mm                   926156 non-null  float64
 51  total_listing_count_yy                   926094 non-null  float64
 52  pending_ratio                            862095 non-null  float64
 53  pending_ratio_mm                         849376 non-null  float64
 54  pending_ratio_yy                         820766 non-null  float64
dtypes: float64(51), int64(1), object(3)
memory usage: 395.7+ MB

In [11]:
combo_df = combo_df.fillna(0)
combo_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 926158 entries, 0 to 926157
Data columns (total 55 columns):
 #   Column                                   Non-Null Count   Dtype
---  ------                                   --------------   -----
 0   month_date_yyyymm                        926158 non-null  object
 1   postal_code                              926158 non-null  int64
 2   state_x                                  926158 non-null  object
 3   city_name_x                              926158 non-null  object
 4   nielsen_hh_rank                          926158 non-null  float64
 5   hotness_rank                             926158 non-null  float64
 6   hotness_rank_mm                          926158 non-null  float64
 7   hotness_rank_yy                          926158 non-null  float64
 8   hotness_score                            926158 non-null  float64
 9   supply_score                             926158 non-null  float64
 10  demand_score                             926158 non-null  float64
 11  median_days_on_market_x                  926158 non-null  float64
 12  median_days_on_market_mm_x               926158 non-null  float64
 13  median_dom_mm_day                        926158 non-null  float64
 14  median_days_on_market_yy_x               926158 non-null  float64
 15  median_dom_yy_day                        926158 non-null  float64
 16  median_dom_vs_us                         926158 non-null  float64
 17  ldp_unique_viewers_per_property_mm       926158 non-null  float64
 18  ldp_unique_viewers_per_property_yy       926158 non-null  float64
 19  ldp_unique_viewers_per_property_vs_us    926158 non-null  float64
 20  median_listing_price_x                   926158 non-null  float64
 21  median_listing_price_mm_x                926158 non-null  float64
 22  median_listing_price_yy_x                926158 non-null  float64
 23  median_listing_price_vs_us               926158 non-null  float64
 24  quality_flag_x                           926158 non-null  float64
 25  active_listing_count                     926158 non-null  float64
 26  active_listing_count_mm                  926158 non-null  float64
 27  active_listing_count_yy                  926158 non-null  float64
 28  new_listing_count                        926158 non-null  float64
 29  new_listing_count_mm                     926158 non-null  float64
 30  new_listing_count_yy                     926158 non-null  float64
 31  price_increased_count                    926158 non-null  float64
 32  price_increased_count_mm                 926158 non-null  float64
 33  price_increased_count_yy                 926158 non-null  float64
 34  price_reduced_count                      926158 non-null  float64
 35  price_reduced_count_mm                   926158 non-null  float64
 36  price_reduced_count_yy                   926158 non-null  float64
 37  pending_listing_count                    926158 non-null  float64
 38  pending_listing_count_mm                 926158 non-null  float64
 39  pending_listing_count_yy                 926158 non-null  float64
 40  median_listing_price_per_square_foot     926158 non-null  float64
 41  median_listing_price_per_square_foot_mm  926158 non-null  float64
 42  median_listing_price_per_square_foot_yy  926158 non-null  float64
 43  median_square_feet                       926158 non-null  float64
 44  median_square_feet_mm                    926158 non-null  float64
 45  median_square_feet_yy                    926158 non-null  float64
 46  average_listing_price                    926158 non-null  float64
 47  average_listing_price_mm                 926158 non-null  float64
 48  average_listing_price_yy                 926158 non-null  float64
 49  total_listing_count                      926158 non-null  float64
 50  total_listing_count_mm                   926158 non-null  float64
 51  total_listing_count_yy                   926158 non-null  float64
 52  pending_ratio                            926158 non-null  float64
 53  pending_ratio_mm                         926158 non-null  float64
 54  pending_ratio_yy                         926158 non-null  float64
dtypes: float64(51), int64(1), object(3)
memory usage: 395.7+ MB

In [12]:
print(combo_df.columns)

Index(['month_date_yyyymm', 'postal_code', 'state_x', 'city_name_x',
       'nielsen_hh_rank', 'hotness_rank', 'hotness_rank_mm', 'hotness_rank_yy',
       'hotness_score', 'supply_score', 'demand_score',
       'median_days_on_market_x', 'median_days_on_market_mm_x',
       'median_dom_mm_day', 'median_days_on_market_yy_x', 'median_dom_yy_day',
       'median_dom_vs_us', 'ldp_unique_viewers_per_property_mm',
       'ldp_unique_viewers_per_property_yy',
       'ldp_unique_viewers_per_property_vs_us', 'median_listing_price_x',
       'median_listing_price_mm_x', 'median_listing_price_yy_x',
       'median_listing_price_vs_us', 'quality_flag_x', 'active_listing_count',
       'active_listing_count_mm', 'active_listing_count_yy',
       'new_listing_count', 'new_listing_count_mm', 'new_listing_count_yy',
       'price_increased_count', 'price_increased_count_mm',
       'price_increased_count_yy', 'price_reduced_count',
       'price_reduced_count_mm', 'price_reduced_count_yy',
       'pending_listing_count', 'pending_listing_count_mm',
       'pending_listing_count_yy', 'median_listing_price_per_square_foot',
       'median_listing_price_per_square_foot_mm',
       'median_listing_price_per_square_foot_yy', 'median_square_feet',
       'median_square_feet_mm', 'median_square_feet_yy',
       'average_listing_price', 'average_listing_price_mm',
       'average_listing_price_yy', 'total_listing_count',
       'total_listing_count_mm', 'total_listing_count_yy', 'pending_ratio',
       'pending_ratio_mm', 'pending_ratio_yy'],
      dtype='object')

In [13]:
# create a new dataframe for only the ML necessary columns
# remove unnecessary columns
column_to_delete = ['quality_flag_x', 'median_listing_price_vs_us', 'median_dom_vs_us',
    'ldp_unique_viewers_per_property_mm', 'ldp_unique_viewers_per_property_yy', 
    'ldp_unique_viewers_per_property_vs_us', 'median_square_feet', 
    'median_square_feet_mm', 'median_square_feet_yy', 'state_x', 'city_name_x']

# delete colujns fro mthe dataframe
combo_df.drop(columns=column_to_delete, inplace=True)

combo_df.head()

,month_date_yyyymm,postal_code,nielsen_hh_rank,hotness_rank,hotness_rank_mm,hotness_rank_yy,hotness_score,supply_score,demand_score,median_days_on_market_x,...,median_listing_price_per_square_foot_yy,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy
0,2023-09,14450,998.0,1.0,-5.0,0.0,99.978698,99.974438,99.982958,7.0,...,0.0770,439999.0,-0.1090,0.1193,26.0,0.1556,0.0000,0.1667,0.0691,-0.0476
1,2023-09,4106,3627.0,2.0,-2.0,0.0,99.923313,99.906271,99.940354,9.0,...,0.2092,669841.0,0.0503,0.0367,27.0,0.2857,0.6875,0.2727,0.1675,0.0327
2,2023-09,14624,1837.0,3.0,-4.0,1.0,99.919052,99.965917,99.872188,8.0,...,0.0734,293467.0,0.0970,0.1037,20.0,-0.0476,-0.1837,0.1765,0.0376,0.0602
3,2023-09,6111,3095.0,4.0,-1064.0,-15.0,99.897751,99.838105,99.957396,10.0,...,0.1423,307199.0,-0.0268,-0.0417,65.0,-0.0299,-0.3085,3.2667,-0.0146,0.9274
4,2023-09,1970,884.0,5.0,-7.0,-5.0,99.893490,99.889230,99.897751,9.5,...,0.1996,543278.0,0.0739,0.0137,35.0,0.4583,-0.3069,0.4000,0.0176,0.0667

In [14]:
# convert the month_date_yyyymm column to a date formate then convert to a reference point of months to the stating date
combo_df['month_date_yyyymm'] = pd.to_datetime(combo_df['month_date_yyyymm'],format='%Y-%m')

# determine the earliest date from the dataset
early_date = combo_df['month_date_yyyymm'].min()

# calculate the # of months since the earliest date
combo_df['months_since_reference'] = (
    (combo_df['month_date_yyyymm'].dt.year - early_date.year) * 12 +
    combo_df['month_date_yyyymm'].dt.month - early_date.month
)

combo_df.head(20)

,month_date_yyyymm,postal_code,nielsen_hh_rank,hotness_rank,hotness_rank_mm,hotness_rank_yy,hotness_score,supply_score,demand_score,median_days_on_market_x,...,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,months_since_reference
0,2023-09-01,14450,998.0,1.0,-5.0,0.0,99.978698,99.974438,99.982958,7.0,...,439999.0,-0.1090,0.1193,26.0,0.1556,0.0000,0.1667,0.0691,-0.0476,73
1,2023-09-01,4106,3627.0,2.0,-2.0,0.0,99.923313,99.906271,99.940354,9.0,...,669841.0,0.0503,0.0367,27.0,0.2857,0.6875,0.2727,0.1675,0.0327,73
2,2023-09-01,14624,1837.0,3.0,-4.0,1.0,99.919052,99.965917,99.872188,8.0,...,293467.0,0.0970,0.1037,20.0,-0.0476,-0.1837,0.1765,0.0376,0.0602,73
3,2023-09-01,6111,3095.0,4.0,-1064.0,-15.0,99.897751,99.838105,99.957396,10.0,...,307199.0,-0.0268,-0.0417,65.0,-0.0299,-0.3085,3.2667,-0.0146,0.9274,73
4,2023-09-01,1970,884.0,5.0,-7.0,-5.0,99.893490,99.889230,99.897751,9.5,...,543278.0,0.0739,0.0137,35.0,0.4583,-0.3069,0.4000,0.0176,0.0667,73
5,2023-09-01,1876,3610.0,6.0,0.0,-329.0,99.889230,100.000000,99.778459,6.0,...,620607.0,0.0076,-0.0287,22.0,0.3750,-0.1538,0.2941,-0.1604,-0.1059,73
6,2023-09-01,14617,4769.0,7.0,5.0,0.0,99.867928,99.906271,99.829584,9.0,...,224148.0,-0.0937,0.0366,20.0,-0.0476,0.8182,0.1176,-0.0490,0.0176,73
7,2023-09-01,1845,3507.0,8.0,0.0,-47.0,99.846626,99.838105,99.855147,10.0,...,720940.0,0.0067,-0.0714,19.0,-0.1556,-0.3968,0.4000,-0.0138,0.0939,73
8,2023-09-01,1960,340.0,9.0,0.0,-8.0,99.791241,99.906271,99.676210,9.0,...,617188.0,-0.0356,-0.0593,31.0,1.0667,-0.0882,0.6111,0.2475,0.1736,73
9,2023-09-01,1915,1362.0,10.0,-321.0,-5.0,99.778459,99.693252,99.863667,13.5,...,1809242.0,0.2517,0.1932,21.0,-0.0870,-0.4000,0.2778,-0.0833,0.0364,73
10,2023-09-01,3038,2723.0,11.0,2.0,-664.0,99.740116,99.667689,99.812543,14.5,...,555268.0,0.0253,-0.0793,35.0,-0.1358,-0.2135,1.0588,0.1541,0.2629,73
11,2023-09-01,7043,8996.0,12.0,0.0,-2988.0,99.680470,99.710293,99.650648,13.0,...,1283607.0,0.3536,0.1922,19.0,-0.0732,-0.1915,0.9091,-0.4798,0.1399,73
12,2023-09-01,43230,204.0,13.0,-1.0,-8.0,99.650648,99.752897,99.548398,12.0,...,345266.0,0.0030,-0.1146,81.0,-0.0690,-0.2098,1.5313,-0.0956,0.5118,73
13,2023-09-01,18017,1981.0,14.0,-17.0,-25.0,99.642127,99.744376,99.539877,12.5,...,423648.0,-0.0469,-0.0307,27.0,-0.1429,-0.2500,0.3684,-0.1089,0.1684,73
14,2023-09-01,4210,4655.0,15.0,2.0,9.0,99.591002,99.752897,99.429107,12.0,...,379809.0,-0.0586,0.0486,37.0,0.2542,0.1212,0.4800,-0.3587,0.1467,73
15,2023-09-01,3054,4490.0,16.0,-14.0,10.0,99.539877,99.752897,99.326858,12.0,...,551969.0,-0.0310,0.1659,33.0,-0.0704,-0.1200,0.5714,-0.2091,-0.0195,73
16,2023-09-01,1880,3954.0,17.0,0.0,-42.0,99.531357,99.974438,99.088275,7.0,...,702359.0,-0.1248,-0.1112,20.0,0.4286,-0.4118,0.3333,-0.1404,0.0692,73
17,2023-09-01,14626,2673.0,18.0,-8.0,-85.0,99.514315,99.906271,99.122359,9.0,...,304381.0,-0.0500,0.1032,21.0,-0.1765,-0.3226,0.2222,0.0859,0.0926,73
18,2023-09-01,4103,2484.0,19.0,18.0,-726.0,99.493013,98.994547,99.991479,17.0,...,612528.0,0.0033,0.0363,27.0,0.2000,-0.2500,0.3333,-0.0490,0.0702,73
19,2023-09-01,6492,1132.0,20.0,-112.0,-33.0,99.407805,98.892297,99.923313,17.5,...,399395.0,0.0534,-0.0641,82.0,0.0649,-0.2264,2.2800,-0.5450,0.2941,73

In [15]:
# double check beginning of data for month reference
combo_df.tail(20)

,month_date_yyyymm,postal_code,nielsen_hh_rank,hotness_rank,hotness_rank_mm,hotness_rank_yy,hotness_score,supply_score,demand_score,median_days_on_market_x,...,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,months_since_reference
926138,2017-08-01,54832,26109.0,16066.0,0.0,0.0,0.826755,1.448374,0.205135,137.50,...,208617.0,-0.0148,0.0246,14.0,-0.0667,0.1667,0.1538,-0.0769,-0.2462,0
926139,2017-08-01,24938,20804.0,16066.0,0.0,0.0,0.826755,1.044322,0.609188,144.50,...,470155.0,0.0951,0.5660,12.0,-0.0769,-0.0400,0.0833,0.0000,0.0000,0
926140,2017-08-01,97869,21583.0,16069.0,0.0,0.0,0.817430,0.882700,0.752160,148.50,...,208838.0,-0.0422,0.4344,17.0,0.2143,0.0303,0.0968,0.0199,0.0343,0
926141,2017-08-01,38922,15072.0,16070.0,0.0,0.0,0.758376,0.814322,0.702431,150.50,...,87503.0,-0.0007,0.0178,17.0,-0.0294,0.8333,0.0625,0.0000,-0.0625,0
926142,2017-08-01,55708,22314.0,16071.0,0.0,0.0,0.733512,0.105675,1.361348,194.75,...,165495.0,-0.0125,-0.2329,28.0,-0.0667,-0.0345,0.0556,-0.0556,0.0198,0
926143,2017-08-01,85320,24261.0,16072.0,0.0,0.0,0.686890,1.361348,0.012432,138.50,...,377900.0,-0.0124,0.1353,15.0,0.0714,0.0714,0.0000,0.0000,0.0000,0
926144,2017-08-01,54527,22113.0,16073.0,0.0,0.0,0.680674,0.062162,1.299186,208.50,...,157065.0,0.5461,-0.0870,30.0,-0.0484,-0.0328,0.0357,-0.0333,0.0029,0
926145,2017-08-01,7501,3809.0,16074.0,0.0,0.0,0.671350,0.634052,0.708647,155.25,...,169819.0,0.0089,-0.0220,49.0,-0.0102,-0.1565,0.0000,0.0000,0.0000,0
926146,2017-08-01,23432,20200.0,16075.0,0.0,0.0,0.668241,0.180270,1.156213,182.00,...,458797.0,-0.0020,0.1151,37.0,0.0000,-0.3148,0.0000,0.0000,0.0000,0
926147,2017-08-01,39851,17976.0,16076.0,0.0,0.0,0.662025,0.124324,1.199726,191.25,...,234632.0,-0.0878,-0.0667,19.0,0.1875,0.2258,0.0571,-0.0054,-0.0074,0
926148,2017-08-01,78361,13548.0,16078.0,0.0,0.0,0.624728,0.714863,0.534593,153.50,...,288316.0,0.0218,1.6880,20.0,-0.0476,-0.2453,0.1111,0.0000,-0.0707,0
926149,2017-08-01,27874,13772.0,16079.0,0.0,0.0,0.618512,0.006216,1.230807,310.50,...,63140.0,0.1204,-0.5411,21.0,0.0000,1.3333,0.0500,-0.0553,-0.0750,0
926150,2017-08-01,96041,16443.0,16081.0,0.0,0.0,0.590539,0.913781,0.267297,147.25,...,521246.0,0.0354,0.2548,26.0,-0.2778,0.3000,0.0612,-0.0678,-0.1888,0
926151,2017-08-01,79849,9817.0,16082.0,0.0,0.0,0.481755,0.944862,0.018649,146.50,...,94143.0,0.0077,-0.3355,39.0,0.0405,1.2000,0.4528,-0.0272,-0.0888,0
926152,2017-08-01,31903,6098.0,16083.0,0.0,0.0,0.459999,0.304594,0.615404,169.00,...,36125.0,-0.0138,-0.1355,55.0,-0.1129,-0.0090,0.0000,0.0000,0.0000,0
926153,2017-08-01,10006,11956.0,16084.0,0.0,0.0,0.366756,0.491080,0.242432,159.75,...,4555490.0,0.0871,-0.0263,109.0,-0.0726,0.3232,0.7724,0.1913,0.1091,0
926154,2017-08-01,83113,17292.0,16085.0,0.0,0.0,0.351215,0.217567,0.484864,178.00,...,203370.0,0.0368,-0.0536,47.0,0.0333,0.4531,0.0698,-0.0017,0.0031,0
926155,2017-08-01,96024,22139.0,16086.0,0.0,0.0,0.298378,0.180270,0.416485,182.00,...,516872.0,-0.0147,0.3181,23.0,0.0714,0.1842,0.0465,-0.1114,-0.2035,0
926156,2017-08-01,87829,26077.0,16087.0,0.0,0.0,0.254864,0.236216,0.273513,174.50,...,297944.0,0.0566,0.2190,20.0,-0.0476,0.4286,0.0526,0.0026,0.0000,0
926157,2017-08-01,36108,6350.0,16088.0,0.0,0.0,0.087027,0.024865,0.149189,221.50,...,56415.0,0.2576,-0.1454,71.0,0.0143,0.3524,0.2119,0.0424,0.0828,0

In [17]:
combo_df.to_csv('../CSV Files/Combined_ML.csv', index=False)